// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_runs.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAgentTaskWaitDependency = `-- name: AddAgentTaskWaitDependency :exec
INSERT INTO agent_task_wait_dependencies(run_id,dependency_id) VALUES ($1,$2)
`

type AddAgentTaskWaitDependencyParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	DependencyID pgtype.UUID `json:"dependency_id"`
}

func (q *Queries) AddAgentTaskWaitDependency(ctx context.Context, arg AddAgentTaskWaitDependencyParams) error {
	_, err := q.db.Exec(ctx, addAgentTaskWaitDependency, arg.RunID, arg.DependencyID)
	return err
}

const agentTaskCheckpointMatches = `-- name: AgentTaskCheckpointMatches :one
SELECT checkpoint = $1::jsonb FROM agent_task_calls WHERE id = $2
`

type AgentTaskCheckpointMatchesParams struct {
	Checkpoint []byte      `json:"checkpoint"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) AgentTaskCheckpointMatches(ctx context.Context, arg AgentTaskCheckpointMatchesParams) (bool, error) {
	row := q.db.QueryRow(ctx, agentTaskCheckpointMatches, arg.Checkpoint, arg.ID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const agentTaskWaitReady = `-- name: AgentTaskWaitReady :one
SELECT (w.deadline <= now() OR
 CASE WHEN w.request ->> 'mode' = 'any' THEN EXISTS (
 SELECT 1 FROM agent_task_wait_dependencies d JOIN agent_task_calls c ON c.id = d.dependency_id
 WHERE d.run_id = w.run_id AND c.completed_at IS NOT NULL)
 ELSE NOT EXISTS (SELECT 1 FROM agent_task_wait_dependencies d JOIN agent_task_calls c ON c.id = d.dependency_id
 WHERE d.run_id = w.run_id AND c.completed_at IS NULL) END)::boolean
FROM agent_task_waits w WHERE w.run_id = $1
`

func (q *Queries) AgentTaskWaitReady(ctx context.Context, runID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, agentTaskWaitReady, runID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const chargeAgentTaskBudget = `-- name: ChargeAgentTaskBudget :exec
UPDATE agent_task_calls SET steps = steps + $1::bigint,tokens = tokens + $2::bigint,updated_at = now()
WHERE id = $3 OR id = $4
`

type ChargeAgentTaskBudgetParams struct {
	Steps  int64       `json:"steps"`
	Tokens int64       `json:"tokens"`
	ID     pgtype.UUID `json:"id"`
	RootID pgtype.UUID `json:"root_id"`
}

func (q *Queries) ChargeAgentTaskBudget(ctx context.Context, arg ChargeAgentTaskBudgetParams) error {
	_, err := q.db.Exec(ctx, chargeAgentTaskBudget,
		arg.Steps,
		arg.Tokens,
		arg.ID,
		arg.RootID,
	)
	return err
}

const claimAgentTaskCall = `-- name: ClaimAgentTaskCall :one
UPDATE agent_task_calls SET status = 'running',owner_token = $1,runtime_generation = $2,
started_at = coalesce(started_at,now()),updated_at = now()
WHERE id = $3 AND status = 'queued' AND cancel_requested_at IS NULL RETURNING id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at
`

type ClaimAgentTaskCallParams struct {
	OwnerToken        pgtype.UUID `json:"owner_token"`
	RuntimeGeneration int64       `json:"runtime_generation"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) ClaimAgentTaskCall(ctx context.Context, arg ClaimAgentTaskCallParams) (AgentTaskCall, error) {
	row := q.db.QueryRow(ctx, claimAgentTaskCall, arg.OwnerToken, arg.RuntimeGeneration, arg.ID)
	var i AgentTaskCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.DefinitionSnapshot,
		&i.SubagentSnapshots,
		&i.RequestID,
		&i.RequestPayload,
		&i.Message,
		&i.RootID,
		&i.ParentID,
		&i.ParentToolCallID,
		&i.Status,
		&i.Reply,
		&i.Error,
		&i.Steps,
		&i.Tokens,
		&i.StepLimit,
		&i.TokenLimit,
		&i.Deadline,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MaxConcurrency,
		&i.MaxSubagentCalls,
		&i.MaxConcurrentSubagents,
		&i.OwnerToken,
		&i.RuntimeGeneration,
		&i.Checkpoint,
		&i.CheckpointRevision,
		&i.CheckpointUpdatedAt,
		&i.CancelRequestedAt,
		&i.RecoveryNotice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAgentTaskCall = `-- name: CreateAgentTaskCall :one
INSERT INTO agent_task_calls(id,session_id,agent_id,definition,contract_hash,definition_snapshot,subagent_snapshots,request_id,request_payload,message,
 root_id,parent_id,parent_tool_call_id,status,error,steps,tokens,step_limit,token_limit,deadline,attempts,max_attempts,max_concurrency,
 max_subagent_calls,max_concurrent_subagents,runtime_generation,checkpoint_revision,recovery_notice,created_at,updated_at,enqueued_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
 $11,$12,$13,'queued','',0,0,$14,$15,$16,1,$17,$18,
 $19,$20,$21,0,'',now(),now(),clock_timestamp()) RETURNING id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at
`

type CreateAgentTaskCallParams struct {
	ID                     pgtype.UUID        `json:"id"`
	SessionID              pgtype.UUID        `json:"session_id"`
	AgentID                pgtype.UUID        `json:"agent_id"`
	Definition             string             `json:"definition"`
	ContractHash           string             `json:"contract_hash"`
	DefinitionSnapshot     []byte             `json:"definition_snapshot"`
	SubagentSnapshots      []byte             `json:"subagent_snapshots"`
	RequestID              string             `json:"request_id"`
	RequestPayload         []byte             `json:"request_payload"`
	Message                string             `json:"message"`
	RootID                 pgtype.UUID        `json:"root_id"`
	ParentID               pgtype.UUID        `json:"parent_id"`
	ParentToolCallID       pgtype.Text        `json:"parent_tool_call_id"`
	StepLimit              int64              `json:"step_limit"`
	TokenLimit             int64              `json:"token_limit"`
	Deadline               pgtype.Timestamptz `json:"deadline"`
	MaxAttempts            int32              `json:"max_attempts"`
	MaxConcurrency         int32              `json:"max_concurrency"`
	MaxSubagentCalls       int32              `json:"max_subagent_calls"`
	MaxConcurrentSubagents int32              `json:"max_concurrent_subagents"`
	RuntimeGeneration      int64              `json:"runtime_generation"`
}

func (q *Queries) CreateAgentTaskCall(ctx context.Context, arg CreateAgentTaskCallParams) (AgentTaskCall, error) {
	row := q.db.QueryRow(ctx, createAgentTaskCall,
		arg.ID,
		arg.SessionID,
		arg.AgentID,
		arg.Definition,
		arg.ContractHash,
		arg.DefinitionSnapshot,
		arg.SubagentSnapshots,
		arg.RequestID,
		arg.RequestPayload,
		arg.Message,
		arg.RootID,
		arg.ParentID,
		arg.ParentToolCallID,
		arg.StepLimit,
		arg.TokenLimit,
		arg.Deadline,
		arg.MaxAttempts,
		arg.MaxConcurrency,
		arg.MaxSubagentCalls,
		arg.MaxConcurrentSubagents,
		arg.RuntimeGeneration,
	)
	var i AgentTaskCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.DefinitionSnapshot,
		&i.SubagentSnapshots,
		&i.RequestID,
		&i.RequestPayload,
		&i.Message,
		&i.RootID,
		&i.ParentID,
		&i.ParentToolCallID,
		&i.Status,
		&i.Reply,
		&i.Error,
		&i.Steps,
		&i.Tokens,
		&i.StepLimit,
		&i.TokenLimit,
		&i.Deadline,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MaxConcurrency,
		&i.MaxSubagentCalls,
		&i.MaxConcurrentSubagents,
		&i.OwnerToken,
		&i.RuntimeGeneration,
		&i.Checkpoint,
		&i.CheckpointRevision,
		&i.CheckpointUpdatedAt,
		&i.CancelRequestedAt,
		&i.RecoveryNotice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAgentTaskConversation = `-- name: CreateAgentTaskConversation :one
INSERT INTO agent_conversations (agent_id, user_id, source, title, metadata, settings)
VALUES ($1, NULL, 'application', $2, '{}'::jsonb, '{}'::jsonb) RETURNING id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at, user_activity_at, notification_route_lost_at
`

type CreateAgentTaskConversationParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Title   string      `json:"title"`
}

func (q *Queries) CreateAgentTaskConversation(ctx context.Context, arg CreateAgentTaskConversationParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, createAgentTaskConversation, arg.AgentID, arg.Title)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserActivityAt,
		&i.NotificationRouteLostAt,
	)
	return i, err
}

const createAgentTaskSession = `-- name: CreateAgentTaskSession :one
INSERT INTO agent_task_sessions(id,agent_id,definition,contract_hash,created_at)
VALUES ($1,$2,$3,$4,now()) RETURNING id, agent_id, definition, contract_hash, created_at
`

type CreateAgentTaskSessionParams struct {
	ID           pgtype.UUID `json:"id"`
	AgentID      pgtype.UUID `json:"agent_id"`
	Definition   string      `json:"definition"`
	ContractHash string      `json:"contract_hash"`
}

func (q *Queries) CreateAgentTaskSession(ctx context.Context, arg CreateAgentTaskSessionParams) (AgentTaskSession, error) {
	row := q.db.QueryRow(ctx, createAgentTaskSession,
		arg.ID,
		arg.AgentID,
		arg.Definition,
		arg.ContractHash,
	)
	var i AgentTaskSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.CreatedAt,
	)
	return i, err
}

const createAgentTaskWait = `-- name: CreateAgentTaskWait :one
INSERT INTO agent_task_waits(run_id,tool_call_id,request,deadline,created_at)
VALUES ($1,$2,$3,$4,now()) RETURNING run_id, tool_call_id, request, deadline, created_at
`

type CreateAgentTaskWaitParams struct {
	RunID      pgtype.UUID        `json:"run_id"`
	ToolCallID string             `json:"tool_call_id"`
	Request    []byte             `json:"request"`
	Deadline   pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) CreateAgentTaskWait(ctx context.Context, arg CreateAgentTaskWaitParams) (AgentTaskWait, error) {
	row := q.db.QueryRow(ctx, createAgentTaskWait,
		arg.RunID,
		arg.ToolCallID,
		arg.Request,
		arg.Deadline,
	)
	var i AgentTaskWait
	err := row.Scan(
		&i.RunID,
		&i.ToolCallID,
		&i.Request,
		&i.Deadline,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgentTaskWait = `-- name: DeleteAgentTaskWait :exec
DELETE FROM agent_task_waits WHERE run_id = $1
`

func (q *Queries) DeleteAgentTaskWait(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentTaskWait, runID)
	return err
}

const finishAgentTaskCall = `-- name: FinishAgentTaskCall :one
UPDATE agent_task_calls SET status = $1,error = $2,reply = $3,completed_at = now(),updated_at = now()
WHERE id = $4 AND status IN ('queued','running','waiting') RETURNING id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at
`

type FinishAgentTaskCallParams struct {
	Status string      `json:"status"`
	Error  string      `json:"error"`
	Reply  []byte      `json:"reply"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) FinishAgentTaskCall(ctx context.Context, arg FinishAgentTaskCallParams) (AgentTaskCall, error) {
	row := q.db.QueryRow(ctx, finishAgentTaskCall,
		arg.Status,
		arg.Error,
		arg.Reply,
		arg.ID,
	)
	var i AgentTaskCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.DefinitionSnapshot,
		&i.SubagentSnapshots,
		&i.RequestID,
		&i.RequestPayload,
		&i.Message,
		&i.RootID,
		&i.ParentID,
		&i.ParentToolCallID,
		&i.Status,
		&i.Reply,
		&i.Error,
		&i.Steps,
		&i.Tokens,
		&i.StepLimit,
		&i.TokenLimit,
		&i.Deadline,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MaxConcurrency,
		&i.MaxSubagentCalls,
		&i.MaxConcurrentSubagents,
		&i.OwnerToken,
		&i.RuntimeGeneration,
		&i.Checkpoint,
		&i.CheckpointRevision,
		&i.CheckpointUpdatedAt,
		&i.CancelRequestedAt,
		&i.RecoveryNotice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const finishAgentTaskExecution = `-- name: FinishAgentTaskExecution :execrows
UPDATE runs SET status = $1,
error_message = CASE WHEN status = 'cancelled' THEN error_message ELSE $2 END,
finished_at = CASE WHEN status = 'cancelled' THEN finished_at ELSE now() END,
duration_ms = CASE WHEN status = 'cancelled' THEN duration_ms ELSE LEAST(EXTRACT(EPOCH FROM (now() - started_at)) * 1000,2147483647)::integer END
WHERE id = $3 AND execution_kind = 'agent'
AND (status = 'running' OR (status = 'cancelled' AND $1::text = 'cancelled'))
`

type FinishAgentTaskExecutionParams struct {
	Status       string      `json:"status"`
	ErrorMessage string      `json:"error_message"`
	ID           pgtype.UUID `json:"id"`
}

// A general cancellation is an accepted terminal CAS, not a task cancel request.
// Preserve its status and timing; no other terminal execution can be overwritten.
func (q *Queries) FinishAgentTaskExecution(ctx context.Context, arg FinishAgentTaskExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAgentTaskExecution, arg.Status, arg.ErrorMessage, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentTaskCall = `-- name: GetAgentTaskCall :one
SELECT id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at FROM agent_task_calls WHERE id = $1
`

func (q *Queries) GetAgentTaskCall(ctx context.Context, id pgtype.UUID) (AgentTaskCall, error) {
	row := q.db.QueryRow(ctx, getAgentTaskCall, id)
	var i AgentTaskCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.DefinitionSnapshot,
		&i.SubagentSnapshots,
		&i.RequestID,
		&i.RequestPayload,
		&i.Message,
		&i.RootID,
		&i.ParentID,
		&i.ParentToolCallID,
		&i.Status,
		&i.Reply,
		&i.Error,
		&i.Steps,
		&i.Tokens,
		&i.StepLimit,
		&i.TokenLimit,
		&i.Deadline,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MaxConcurrency,
		&i.MaxSubagentCalls,
		&i.MaxConcurrentSubagents,
		&i.OwnerToken,
		&i.RuntimeGeneration,
		&i.Checkpoint,
		&i.CheckpointRevision,
		&i.CheckpointUpdatedAt,
		&i.CancelRequestedAt,
		&i.RecoveryNotice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAgentTaskLease = `-- name: GetAgentTaskLease :one
SELECT conversation_id, run_id, owner_token, lease_until, cancel_requested FROM conversation_run_leases WHERE run_id = $1
`

func (q *Queries) GetAgentTaskLease(ctx context.Context, runID pgtype.UUID) (ConversationRunLease, error) {
	row := q.db.QueryRow(ctx, getAgentTaskLease, runID)
	var i ConversationRunLease
	err := row.Scan(
		&i.ConversationID,
		&i.RunID,
		&i.OwnerToken,
		&i.LeaseUntil,
		&i.CancelRequested,
	)
	return i, err
}

const getAgentTaskRequest = `-- name: GetAgentTaskRequest :one
SELECT id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at FROM agent_task_calls WHERE agent_id = $1 AND definition = $2 AND request_id = $3
`

type GetAgentTaskRequestParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	Definition string      `json:"definition"`
	RequestID  string      `json:"request_id"`
}

func (q *Queries) GetAgentTaskRequest(ctx context.Context, arg GetAgentTaskRequestParams) (AgentTaskCall, error) {
	row := q.db.QueryRow(ctx, getAgentTaskRequest, arg.AgentID, arg.Definition, arg.RequestID)
	var i AgentTaskCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.DefinitionSnapshot,
		&i.SubagentSnapshots,
		&i.RequestID,
		&i.RequestPayload,
		&i.Message,
		&i.RootID,
		&i.ParentID,
		&i.ParentToolCallID,
		&i.Status,
		&i.Reply,
		&i.Error,
		&i.Steps,
		&i.Tokens,
		&i.StepLimit,
		&i.TokenLimit,
		&i.Deadline,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MaxConcurrency,
		&i.MaxSubagentCalls,
		&i.MaxConcurrentSubagents,
		&i.OwnerToken,
		&i.RuntimeGeneration,
		&i.Checkpoint,
		&i.CheckpointRevision,
		&i.CheckpointUpdatedAt,
		&i.CancelRequestedAt,
		&i.RecoveryNotice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAgentTaskSession = `-- name: GetAgentTaskSession :one
SELECT id, agent_id, definition, contract_hash, created_at FROM agent_task_sessions WHERE id = $1 AND agent_id = $2 AND definition = $3
`

type GetAgentTaskSessionParams struct {
	ID         pgtype.UUID `json:"id"`
	AgentID    pgtype.UUID `json:"agent_id"`
	Definition string      `json:"definition"`
}

func (q *Queries) GetAgentTaskSession(ctx context.Context, arg GetAgentTaskSessionParams) (AgentTaskSession, error) {
	row := q.db.QueryRow(ctx, getAgentTaskSession, arg.ID, arg.AgentID, arg.Definition)
	var i AgentTaskSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentTaskSpawn = `-- name: GetAgentTaskSpawn :one
SELECT id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at FROM agent_task_calls WHERE parent_id = $1 AND parent_tool_call_id = $2
`

type GetAgentTaskSpawnParams struct {
	ParentID         pgtype.UUID `json:"parent_id"`
	ParentToolCallID pgtype.Text `json:"parent_tool_call_id"`
}

func (q *Queries) GetAgentTaskSpawn(ctx context.Context, arg GetAgentTaskSpawnParams) (AgentTaskCall, error) {
	row := q.db.QueryRow(ctx, getAgentTaskSpawn, arg.ParentID, arg.ParentToolCallID)
	var i AgentTaskCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.DefinitionSnapshot,
		&i.SubagentSnapshots,
		&i.RequestID,
		&i.RequestPayload,
		&i.Message,
		&i.RootID,
		&i.ParentID,
		&i.ParentToolCallID,
		&i.Status,
		&i.Reply,
		&i.Error,
		&i.Steps,
		&i.Tokens,
		&i.StepLimit,
		&i.TokenLimit,
		&i.Deadline,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MaxConcurrency,
		&i.MaxSubagentCalls,
		&i.MaxConcurrentSubagents,
		&i.OwnerToken,
		&i.RuntimeGeneration,
		&i.Checkpoint,
		&i.CheckpointRevision,
		&i.CheckpointUpdatedAt,
		&i.CancelRequestedAt,
		&i.RecoveryNotice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAgentTaskUsage = `-- name: GetAgentTaskUsage :one
SELECT u.request_id, u.run_id, u.owner_token, u.tokens, u.reported, u.created_at FROM agent_task_usage u JOIN agent_task_calls c ON c.id = u.run_id
WHERE u.request_id = $1 AND c.agent_id = $2
`

type GetAgentTaskUsageParams struct {
	RequestID pgtype.UUID `json:"request_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
}

func (q *Queries) GetAgentTaskUsage(ctx context.Context, arg GetAgentTaskUsageParams) (AgentTaskUsage, error) {
	row := q.db.QueryRow(ctx, getAgentTaskUsage, arg.RequestID, arg.AgentID)
	var i AgentTaskUsage
	err := row.Scan(
		&i.RequestID,
		&i.RunID,
		&i.OwnerToken,
		&i.Tokens,
		&i.Reported,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentTaskWait = `-- name: GetAgentTaskWait :one
SELECT run_id, tool_call_id, request, deadline, created_at FROM agent_task_waits WHERE run_id = $1
`

func (q *Queries) GetAgentTaskWait(ctx context.Context, runID pgtype.UUID) (AgentTaskWait, error) {
	row := q.db.QueryRow(ctx, getAgentTaskWait, runID)
	var i AgentTaskWait
	err := row.Scan(
		&i.RunID,
		&i.ToolCallID,
		&i.Request,
		&i.Deadline,
		&i.CreatedAt,
	)
	return i, err
}

const getScopedAgentTaskCall = `-- name: GetScopedAgentTaskCall :one
SELECT id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at FROM agent_task_calls WHERE id = $1 AND agent_id = $2 AND definition = $3
`

type GetScopedAgentTaskCallParams struct {
	ID         pgtype.UUID `json:"id"`
	AgentID    pgtype.UUID `json:"agent_id"`
	Definition string      `json:"definition"`
}

func (q *Queries) GetScopedAgentTaskCall(ctx context.Context, arg GetScopedAgentTaskCallParams) (AgentTaskCall, error) {
	row := q.db.QueryRow(ctx, getScopedAgentTaskCall, arg.ID, arg.AgentID, arg.Definition)
	var i AgentTaskCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.DefinitionSnapshot,
		&i.SubagentSnapshots,
		&i.RequestID,
		&i.RequestPayload,
		&i.Message,
		&i.RootID,
		&i.ParentID,
		&i.ParentToolCallID,
		&i.Status,
		&i.Reply,
		&i.Error,
		&i.Steps,
		&i.Tokens,
		&i.StepLimit,
		&i.TokenLimit,
		&i.Deadline,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MaxConcurrency,
		&i.MaxSubagentCalls,
		&i.MaxConcurrentSubagents,
		&i.OwnerToken,
		&i.RuntimeGeneration,
		&i.Checkpoint,
		&i.CheckpointRevision,
		&i.CheckpointUpdatedAt,
		&i.CancelRequestedAt,
		&i.RecoveryNotice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const isAdmittedAgentTaskLive = `-- name: IsAdmittedAgentTaskLive :one
SELECT EXISTS (SELECT 1 FROM agent_task_calls c
 JOIN runs r ON r.id = c.id AND r.agent_id = c.agent_id AND r.caller_conversation_id = c.session_id
 JOIN execution_origins o ON o.id = r.origin_id AND o.agent_id = c.agent_id AND o.actor = 'app'
 JOIN agents a ON a.id = c.agent_id AND a.agent_token_version = c.runtime_generation AND a.status IN ('active','building')
 JOIN agent_runtime_manifests m ON m.agent_id = a.id AND m.token_version = a.agent_token_version
 JOIN conversation_run_leases l ON l.run_id = c.id AND l.conversation_id = c.session_id AND l.owner_token = c.owner_token
 WHERE c.id = $1 AND c.agent_id = $2 AND c.status = 'running' AND r.status = 'running'
 AND r.execution_kind = 'agent' AND c.owner_token = r.runtime_owner_token
 AND l.lease_until > now() AND NOT l.cancel_requested AND c.cancel_requested_at IS NULL
 AND (c.deadline IS NULL OR c.deadline > now())
 AND (c.token_limit = 0 OR c.tokens < c.token_limit)
 AND EXISTS (SELECT 1 FROM agent_task_calls root WHERE root.id = c.root_id
 AND root.cancel_requested_at IS NULL AND root.completed_at IS NULL
 AND (root.deadline IS NULL OR root.deadline > now()) AND (root.token_limit = 0 OR root.tokens < root.token_limit))
 AND m.manifest ->> 'runtimeProtocol' = $3::text
 AND EXISTS (SELECT 1 FROM json_array_elements(m.manifest -> 'agentDefinitions') d
 WHERE d ->> 'slug' = c.definition AND d ->> 'contractHash' = c.contract_hash)
 AND NOT EXISTS (SELECT 1 FROM json_array_elements(c.subagent_snapshots) child WHERE NOT EXISTS (
 SELECT 1 FROM json_array_elements(m.manifest -> 'agentDefinitions') d
 WHERE d ->> 'slug' = child ->> 'slug' AND d ->> 'contractHash' = child ->> 'contractHash')))
`

type IsAdmittedAgentTaskLiveParams struct {
	ID              pgtype.UUID `json:"id"`
	AgentID         pgtype.UUID `json:"agent_id"`
	RuntimeProtocol string      `json:"runtime_protocol"`
}

func (q *Queries) IsAdmittedAgentTaskLive(ctx context.Context, arg IsAdmittedAgentTaskLiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmittedAgentTaskLive, arg.ID, arg.AgentID, arg.RuntimeProtocol)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveAgentTaskCalls = `-- name: ListActiveAgentTaskCalls :many
SELECT id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at FROM agent_task_calls WHERE status IN ('queued','running','waiting') ORDER BY enqueued_at,id
`

func (q *Queries) ListActiveAgentTaskCalls(ctx context.Context) ([]AgentTaskCall, error) {
	rows, err := q.db.Query(ctx, listActiveAgentTaskCalls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTaskCall{}
	for rows.Next() {
		var i AgentTaskCall
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgentID,
			&i.Definition,
			&i.ContractHash,
			&i.DefinitionSnapshot,
			&i.SubagentSnapshots,
			&i.RequestID,
			&i.RequestPayload,
			&i.Message,
			&i.RootID,
			&i.ParentID,
			&i.ParentToolCallID,
			&i.Status,
			&i.Reply,
			&i.Error,
			&i.Steps,
			&i.Tokens,
			&i.StepLimit,
			&i.TokenLimit,
			&i.Deadline,
			&i.Attempts,
			&i.MaxAttempts,
			&i.MaxConcurrency,
			&i.MaxSubagentCalls,
			&i.MaxConcurrentSubagents,
			&i.OwnerToken,
			&i.RuntimeGeneration,
			&i.Checkpoint,
			&i.CheckpointRevision,
			&i.CheckpointUpdatedAt,
			&i.CancelRequestedAt,
			&i.RecoveryNotice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnqueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTaskCalls = `-- name: ListAgentTaskCalls :many
SELECT id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at FROM agent_task_calls WHERE agent_id = $1 AND definition = $2
AND ($3::text = '' OR contract_hash = $3)
AND ($4::text = '' OR status = $4) AND ($5::uuid IS NULL OR session_id = $5)
AND ($6::timestamptz IS NULL OR (created_at,id) < ($6,$7::uuid))
ORDER BY created_at DESC,id DESC LIMIT $8
`

type ListAgentTaskCallsParams struct {
	AgentID      pgtype.UUID        `json:"agent_id"`
	Definition   string             `json:"definition"`
	ContractHash string             `json:"contract_hash"`
	Status       string             `json:"status"`
	SessionID    pgtype.UUID        `json:"session_id"`
	CursorTime   pgtype.Timestamptz `json:"cursor_time"`
	CursorID     pgtype.UUID        `json:"cursor_id"`
	Lim          int32              `json:"lim"`
}

func (q *Queries) ListAgentTaskCalls(ctx context.Context, arg ListAgentTaskCallsParams) ([]AgentTaskCall, error) {
	rows, err := q.db.Query(ctx, listAgentTaskCalls,
		arg.AgentID,
		arg.Definition,
		arg.ContractHash,
		arg.Status,
		arg.SessionID,
		arg.CursorTime,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTaskCall{}
	for rows.Next() {
		var i AgentTaskCall
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgentID,
			&i.Definition,
			&i.ContractHash,
			&i.DefinitionSnapshot,
			&i.SubagentSnapshots,
			&i.RequestID,
			&i.RequestPayload,
			&i.Message,
			&i.RootID,
			&i.ParentID,
			&i.ParentToolCallID,
			&i.Status,
			&i.Reply,
			&i.Error,
			&i.Steps,
			&i.Tokens,
			&i.StepLimit,
			&i.TokenLimit,
			&i.Deadline,
			&i.Attempts,
			&i.MaxAttempts,
			&i.MaxConcurrency,
			&i.MaxSubagentCalls,
			&i.MaxConcurrentSubagents,
			&i.OwnerToken,
			&i.RuntimeGeneration,
			&i.Checkpoint,
			&i.CheckpointRevision,
			&i.CheckpointUpdatedAt,
			&i.CancelRequestedAt,
			&i.RecoveryNotice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnqueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTaskChildren = `-- name: ListAgentTaskChildren :many
SELECT id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at FROM agent_task_calls WHERE parent_id = $1 ORDER BY created_at,id
`

func (q *Queries) ListAgentTaskChildren(ctx context.Context, parentID pgtype.UUID) ([]AgentTaskCall, error) {
	rows, err := q.db.Query(ctx, listAgentTaskChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTaskCall{}
	for rows.Next() {
		var i AgentTaskCall
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgentID,
			&i.Definition,
			&i.ContractHash,
			&i.DefinitionSnapshot,
			&i.SubagentSnapshots,
			&i.RequestID,
			&i.RequestPayload,
			&i.Message,
			&i.RootID,
			&i.ParentID,
			&i.ParentToolCallID,
			&i.Status,
			&i.Reply,
			&i.Error,
			&i.Steps,
			&i.Tokens,
			&i.StepLimit,
			&i.TokenLimit,
			&i.Deadline,
			&i.Attempts,
			&i.MaxAttempts,
			&i.MaxConcurrency,
			&i.MaxSubagentCalls,
			&i.MaxConcurrentSubagents,
			&i.OwnerToken,
			&i.RuntimeGeneration,
			&i.Checkpoint,
			&i.CheckpointRevision,
			&i.CheckpointUpdatedAt,
			&i.CancelRequestedAt,
			&i.RecoveryNotice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnqueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTaskSessionCalls = `-- name: ListAgentTaskSessionCalls :many
SELECT id, session_id, agent_id, definition, contract_hash, definition_snapshot, subagent_snapshots, request_id, request_payload, message, root_id, parent_id, parent_tool_call_id, status, reply, error, steps, tokens, step_limit, token_limit, deadline, attempts, max_attempts, max_concurrency, max_subagent_calls, max_concurrent_subagents, owner_token, runtime_generation, checkpoint, checkpoint_revision, checkpoint_updated_at, cancel_requested_at, recovery_notice, created_at, updated_at, enqueued_at, started_at, completed_at FROM agent_task_calls WHERE session_id = $1 ORDER BY created_at DESC,id DESC
`

func (q *Queries) ListAgentTaskSessionCalls(ctx context.Context, sessionID pgtype.UUID) ([]AgentTaskCall, error) {
	rows, err := q.db.Query(ctx, listAgentTaskSessionCalls, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTaskCall{}
	for rows.Next() {
		var i AgentTaskCall
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgentID,
			&i.Definition,
			&i.ContractHash,
			&i.DefinitionSnapshot,
			&i.SubagentSnapshots,
			&i.RequestID,
			&i.RequestPayload,
			&i.Message,
			&i.RootID,
			&i.ParentID,
			&i.ParentToolCallID,
			&i.Status,
			&i.Reply,
			&i.Error,
			&i.Steps,
			&i.Tokens,
			&i.StepLimit,
			&i.TokenLimit,
			&i.Deadline,
			&i.Attempts,
			&i.MaxAttempts,
			&i.MaxConcurrency,
			&i.MaxSubagentCalls,
			&i.MaxConcurrentSubagents,
			&i.OwnerToken,
			&i.RuntimeGeneration,
			&i.Checkpoint,
			&i.CheckpointRevision,
			&i.CheckpointUpdatedAt,
			&i.CancelRequestedAt,
			&i.RecoveryNotice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnqueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentTaskExecution = `-- name: LockAgentTaskExecution :one
SELECT id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, stdout_log, error_message, error_kind, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at, parent_run_id, llm_tokens_cached, caller_user_id, caller_conversation_id, caller_access, runtime_owner_token, origin_id, execution_kind, resume_run_id FROM runs WHERE id = $1 AND execution_kind = 'agent' FOR UPDATE
`

func (q *Queries) LockAgentTaskExecution(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, lockAgentTaskExecution, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerRef,
		&i.SourceRef,
		&i.InputPayload,
		&i.Actions,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmCostEstimate,
		&i.DurationMs,
		&i.StdoutLog,
		&i.ErrorMessage,
		&i.ErrorKind,
		&i.ExitCode,
		&i.PanicTrace,
		&i.Checkpoint,
		&i.Compacted,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ParentRunID,
		&i.LlmTokensCached,
		&i.CallerUserID,
		&i.CallerConversationID,
		&i.CallerAccess,
		&i.RuntimeOwnerToken,
		&i.OriginID,
		&i.ExecutionKind,
		&i.ResumeRunID,
	)
	return i, err
}

const lockAgentTaskLease = `-- name: LockAgentTaskLease :one
SELECT conversation_id, run_id, owner_token, lease_until, cancel_requested FROM conversation_run_leases WHERE run_id = $1 FOR UPDATE
`

// Lock the lease before the execution row, including expired owners.
func (q *Queries) LockAgentTaskLease(ctx context.Context, runID pgtype.UUID) (ConversationRunLease, error) {
	row := q.db.QueryRow(ctx, lockAgentTaskLease, runID)
	var i ConversationRunLease
	err := row.Scan(
		&i.ConversationID,
		&i.RunID,
		&i.OwnerToken,
		&i.LeaseUntil,
		&i.CancelRequested,
	)
	return i, err
}

const lockAgentTaskOwner = `-- name: LockAgentTaskOwner :one
SELECT c.id, c.session_id, c.agent_id, c.definition, c.contract_hash, c.definition_snapshot, c.subagent_snapshots, c.request_id, c.request_payload, c.message, c.root_id, c.parent_id, c.parent_tool_call_id, c.status, c.reply, c.error, c.steps, c.tokens, c.step_limit, c.token_limit, c.deadline, c.attempts, c.max_attempts, c.max_concurrency, c.max_subagent_calls, c.max_concurrent_subagents, c.owner_token, c.runtime_generation, c.checkpoint, c.checkpoint_revision, c.checkpoint_updated_at, c.cancel_requested_at, c.recovery_notice, c.created_at, c.updated_at, c.enqueued_at, c.started_at, c.completed_at FROM agent_task_calls c JOIN conversation_run_leases l ON l.run_id = c.id AND l.conversation_id = c.session_id
WHERE c.id = $1 AND c.owner_token = $2 AND l.owner_token = c.owner_token
AND c.status = 'running' AND c.cancel_requested_at IS NULL AND NOT l.cancel_requested AND l.lease_until > now()
FOR UPDATE OF c
`

type LockAgentTaskOwnerParams struct {
	ID         pgtype.UUID `json:"id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

func (q *Queries) LockAgentTaskOwner(ctx context.Context, arg LockAgentTaskOwnerParams) (AgentTaskCall, error) {
	row := q.db.QueryRow(ctx, lockAgentTaskOwner, arg.ID, arg.OwnerToken)
	var i AgentTaskCall
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Definition,
		&i.ContractHash,
		&i.DefinitionSnapshot,
		&i.SubagentSnapshots,
		&i.RequestID,
		&i.RequestPayload,
		&i.Message,
		&i.RootID,
		&i.ParentID,
		&i.ParentToolCallID,
		&i.Status,
		&i.Reply,
		&i.Error,
		&i.Steps,
		&i.Tokens,
		&i.StepLimit,
		&i.TokenLimit,
		&i.Deadline,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MaxConcurrency,
		&i.MaxSubagentCalls,
		&i.MaxConcurrentSubagents,
		&i.OwnerToken,
		&i.RuntimeGeneration,
		&i.Checkpoint,
		&i.CheckpointRevision,
		&i.CheckpointUpdatedAt,
		&i.CancelRequestedAt,
		&i.RecoveryNotice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const lockAgentTaskScheduler = `-- name: LockAgentTaskScheduler :exec
SELECT pg_advisory_xact_lock(4705497361458202691)
`

func (q *Queries) LockAgentTaskScheduler(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAgentTaskScheduler)
	return err
}

const parkAgentTaskCall = `-- name: ParkAgentTaskCall :execrows
UPDATE agent_task_calls SET status = 'waiting',updated_at = now() WHERE id = $1 AND owner_token = $2 AND status = 'running'
`

type ParkAgentTaskCallParams struct {
	ID         pgtype.UUID `json:"id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

func (q *Queries) ParkAgentTaskCall(ctx context.Context, arg ParkAgentTaskCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, parkAgentTaskCall, arg.ID, arg.OwnerToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAgentTaskClaim = `-- name: RecordAgentTaskClaim :execrows
INSERT INTO agent_task_claims(owner_token,run_id,session_id,runtime_generation,created_at)
SELECT c.owner_token,c.id,c.session_id,c.runtime_generation,now() FROM agent_task_calls c
WHERE c.id = $1 AND c.owner_token = $2 AND c.status = 'running'
`

type RecordAgentTaskClaimParams struct {
	ID         pgtype.UUID `json:"id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

func (q *Queries) RecordAgentTaskClaim(ctx context.Context, arg RecordAgentTaskClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAgentTaskClaim, arg.ID, arg.OwnerToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAgentTaskUsage = `-- name: RecordAgentTaskUsage :execrows
INSERT INTO agent_task_usage(request_id,run_id,owner_token,tokens,reported,created_at)
SELECT $1,c.id,claim.owner_token,$2,$3,now()
FROM agent_task_claims claim JOIN agent_task_calls c ON c.id = claim.run_id AND c.session_id = claim.session_id
WHERE c.id = $4 AND c.agent_id = $5 AND claim.owner_token = $6
ON CONFLICT (request_id) DO NOTHING
`

type RecordAgentTaskUsageParams struct {
	RequestID  pgtype.UUID `json:"request_id"`
	Tokens     int64       `json:"tokens"`
	Reported   bool        `json:"reported"`
	RunID      pgtype.UUID `json:"run_id"`
	AgentID    pgtype.UUID `json:"agent_id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

func (q *Queries) RecordAgentTaskUsage(ctx context.Context, arg RecordAgentTaskUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAgentTaskUsage,
		arg.RequestID,
		arg.Tokens,
		arg.Reported,
		arg.RunID,
		arg.AgentID,
		arg.OwnerToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestAgentTaskCancellation = `-- name: RequestAgentTaskCancellation :exec
UPDATE agent_task_calls SET cancel_requested_at = coalesce(cancel_requested_at,now()),updated_at = now()
WHERE (id = $1 OR root_id = $1 OR parent_id = $1) AND status IN ('queued','running','waiting')
`

func (q *Queries) RequestAgentTaskCancellation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, requestAgentTaskCancellation, id)
	return err
}

const requestAgentTaskFailure = `-- name: RequestAgentTaskFailure :exec
UPDATE agent_task_calls SET error = $1,cancel_requested_at = coalesce(cancel_requested_at,now()),updated_at = now()
WHERE (id = $2 OR root_id = $2) AND status IN ('queued','running','waiting')
`

type RequestAgentTaskFailureParams struct {
	Error string      `json:"error"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) RequestAgentTaskFailure(ctx context.Context, arg RequestAgentTaskFailureParams) error {
	_, err := q.db.Exec(ctx, requestAgentTaskFailure, arg.Error, arg.ID)
	return err
}

const requeueAgentTaskCall = `-- name: RequeueAgentTaskCall :exec
UPDATE agent_task_calls SET status = 'queued',updated_at = now(),enqueued_at = clock_timestamp(),attempts = attempts + $1::integer,
recovery_notice = $2 WHERE id = $3 AND status IN ('running','waiting')
`

type RequeueAgentTaskCallParams struct {
	Interrupted    int32       `json:"interrupted"`
	RecoveryNotice string      `json:"recovery_notice"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) RequeueAgentTaskCall(ctx context.Context, arg RequeueAgentTaskCallParams) error {
	_, err := q.db.Exec(ctx, requeueAgentTaskCall, arg.Interrupted, arg.RecoveryNotice, arg.ID)
	return err
}

const saveAgentTaskCheckpoint = `-- name: SaveAgentTaskCheckpoint :execrows
UPDATE agent_task_calls SET checkpoint = $1,checkpoint_revision = checkpoint_revision + 1,checkpoint_updated_at = now(),updated_at = now()
WHERE id = $2 AND owner_token = $3 AND status = 'running' AND checkpoint_revision = $4
`

type SaveAgentTaskCheckpointParams struct {
	Checkpoint []byte      `json:"checkpoint"`
	ID         pgtype.UUID `json:"id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
	Revision   int64       `json:"revision"`
}

func (q *Queries) SaveAgentTaskCheckpoint(ctx context.Context, arg SaveAgentTaskCheckpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveAgentTaskCheckpoint,
		arg.Checkpoint,
		arg.ID,
		arg.OwnerToken,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveAgentTaskReply = `-- name: SaveAgentTaskReply :exec
UPDATE agent_task_calls SET reply = $1,updated_at = now() WHERE id = $2
`

type SaveAgentTaskReplyParams struct {
	Reply []byte      `json:"reply"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) SaveAgentTaskReply(ctx context.Context, arg SaveAgentTaskReplyParams) error {
	_, err := q.db.Exec(ctx, saveAgentTaskReply, arg.Reply, arg.ID)
	return err
}
