// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_members.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAppMembers = `-- name: ListAppMembers :many
SELECT u.id, u.email, u.display_name, u.created_at,
       CASE max(CASE g.role WHEN 'admin' THEN 2 WHEN 'user' THEN 1 ELSE 0 END)
           WHEN 2 THEN 'admin' WHEN 1 THEN 'user' ELSE 'public' END::text AS access
FROM users u
JOIN agent_grants g ON g.agent_id = $1 AND (
    g.grantee_id = u.id
    OR (g.grantee_id = $2::uuid AND u.tenant_role = 'admin')
    OR (g.grantee_id = $3::uuid AND u.tenant_role IN ('admin', 'manager'))
    OR (g.grantee_id = $4::uuid AND u.tenant_role IN ('admin', 'manager', 'user'))
)
WHERE $5::timestamptz IS NULL
   OR (u.created_at, u.id) > ($5::timestamptz, $6::uuid)
GROUP BY u.id
ORDER BY u.created_at, u.id
LIMIT $7
`

type ListAppMembersParams struct {
	AgentID        pgtype.UUID        `json:"agent_id"`
	GroupAdmin     pgtype.UUID        `json:"group_admin"`
	GroupManager   pgtype.UUID        `json:"group_manager"`
	GroupUser      pgtype.UUID        `json:"group_user"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageLimit      int32              `json:"page_limit"`
}

type ListAppMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Access      string             `json:"access"`
}

// Expand the same inherited role groups as authz.Principal.GranteeSet.
// The inner join requires an actual grant, including an explicit public grant.
func (q *Queries) ListAppMembers(ctx context.Context, arg ListAppMembersParams) ([]ListAppMembersRow, error) {
	rows, err := q.db.Query(ctx, listAppMembers,
		arg.AgentID,
		arg.GroupAdmin,
		arg.GroupManager,
		arg.GroupUser,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppMembersRow{}
	for rows.Next() {
		var i ListAppMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.Access,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
