// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_admission.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBridgePromptRun = `-- name: CancelBridgePromptRun :execrows
UPDATE runs r SET status = 'cancelled', error_message = 'cancelled by user',
    finished_at = now(), duration_ms = (EXTRACT(EPOCH FROM (now() - r.started_at)) * 1000)::integer
FROM agent_conversations c, bridges b, platform_identities i, users u, execution_origins o
WHERE r.id = $1 AND r.status = 'running' AND r.trigger_type = 'prompt'
  AND r.execution_kind = 'prompt' AND c.id = r.caller_conversation_id
  AND o.id = r.origin_id AND o.ingress = 'bridge' AND o.actor = 'user'
  AND o.auth_epoch = $2::bigint AND o.platform_identity_id = i.id
  AND o.sender_id = $3::text AND o.chat_id = $4::text AND o.bridge_id = b.id
  AND r.agent_id = $5 AND b.agent_id = r.agent_id AND c.agent_id = r.agent_id
  AND r.bridge_id = $6 AND c.bridge_id = r.bridge_id AND b.id = c.bridge_id
  AND r.trigger_ref = c.id::text AND c.source = 'bridge'
  AND c.external_id = $4::text AND $4::text = $3::text
  AND i.platform = b.type AND i.platform_user_id = $3
  AND u.id = i.user_id AND u.id = $7 AND c.user_id = u.id AND r.caller_user_id = u.id
  AND NOT u.must_change_password AND u.auth_epoch = $2
  AND b.status = 'active' AND b.type = 'telegram' AND NOT b.is_system
`

type CancelBridgePromptRunParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	AuthEpoch int64       `json:"auth_epoch"`
	SenderID  string      `json:"sender_id"`
	ChatID    string      `json:"chat_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
	BridgeID  pgtype.UUID `json:"bridge_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CancelBridgePromptRun(ctx context.Context, arg CancelBridgePromptRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBridgePromptRun,
		arg.RunID,
		arg.AuthEpoch,
		arg.SenderID,
		arg.ChatID,
		arg.AgentID,
		arg.BridgeID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelBridgeSystemRun = `-- name: CancelBridgeSystemRun :execrows
UPDATE system_runs r SET status = 'cancelled', error_message = 'cancelled by user', finished_at = now()
FROM system_conversations c, bridges b, platform_identities i, users u
WHERE r.id = $1 AND r.status = 'running' AND r.trigger_type = 'bridge'
  AND r.conversation_id = c.id AND c.source = 'bridge'
  AND c.bridge_id = $2 AND b.id = c.bridge_id AND b.is_system
  AND b.status = 'active' AND b.type = 'telegram'
  AND c.external_id = $3::text AND $3::text = $4::text
  AND i.platform = b.type AND i.platform_user_id = $4
  AND u.id = i.user_id AND u.id = $5 AND r.user_id = u.id AND c.user_id = u.id
  AND NOT u.must_change_password AND u.auth_epoch = $6
`

type CancelBridgeSystemRunParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	BridgeID  pgtype.UUID `json:"bridge_id"`
	ChatID    string      `json:"chat_id"`
	SenderID  string      `json:"sender_id"`
	UserID    pgtype.UUID `json:"user_id"`
	AuthEpoch int64       `json:"auth_epoch"`
}

func (q *Queries) CancelBridgeSystemRun(ctx context.Context, arg CancelBridgeSystemRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBridgeSystemRun,
		arg.RunID,
		arg.BridgeID,
		arg.ChatID,
		arg.SenderID,
		arg.UserID,
		arg.AuthEpoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBridgeConversation = `-- name: GetBridgeConversation :one
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at, user_activity_at, notification_route_lost_at FROM agent_conversations
WHERE agent_id = $1 AND user_id = $2 AND source = 'bridge'
  AND bridge_id = $3 AND external_id = $4
`

type GetBridgeConversationParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	UserID     pgtype.UUID `json:"user_id"`
	BridgeID   pgtype.UUID `json:"bridge_id"`
	ExternalID pgtype.Text `json:"external_id"`
}

func (q *Queries) GetBridgeConversation(ctx context.Context, arg GetBridgeConversationParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, getBridgeConversation,
		arg.AgentID,
		arg.UserID,
		arg.BridgeID,
		arg.ExternalID,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserActivityAt,
		&i.NotificationRouteLostAt,
	)
	return i, err
}
