// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_management_inventory.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeHostManagementInventory = `-- name: AcknowledgeHostManagementInventory :exec
UPDATE host_management_jobs
SET inventory_acknowledged_at = now(), updated_at = now()
WHERE host_id = $1 AND connector_id = $2 AND status = 'succeeded'
  AND inventory_revision <= $3 AND inventory_acknowledged_at IS NULL
`

type AcknowledgeHostManagementInventoryParams struct {
	HostID            pgtype.UUID `json:"host_id"`
	ConnectorID       pgtype.UUID `json:"connector_id"`
	InventoryRevision pgtype.Int8 `json:"inventory_revision"`
}

func (q *Queries) AcknowledgeHostManagementInventory(ctx context.Context, arg AcknowledgeHostManagementInventoryParams) error {
	_, err := q.db.Exec(ctx, acknowledgeHostManagementInventory, arg.HostID, arg.ConnectorID, arg.InventoryRevision)
	return err
}

const recordHostManagementInventoryRevision = `-- name: RecordHostManagementInventoryRevision :one
UPDATE host_management_jobs
SET inventory_revision = $1, updated_at = now()
WHERE id = $2 AND status = 'succeeded' AND kind IN ('connector_update', 'connector_rollback')
RETURNING id, host_id, connector_id, requested_by_user_id, kind, artifact_file_id, input_payload, secret_input, status, output_payload, secret_output, error_message, deadline_at, started_at, completed_at, created_at, updated_at, inventory_revision, inventory_acknowledged_at
`

type RecordHostManagementInventoryRevisionParams struct {
	InventoryRevision pgtype.Int8 `json:"inventory_revision"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) RecordHostManagementInventoryRevision(ctx context.Context, arg RecordHostManagementInventoryRevisionParams) (HostManagementJob, error) {
	row := q.db.QueryRow(ctx, recordHostManagementInventoryRevision, arg.InventoryRevision, arg.ID)
	var i HostManagementJob
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ConnectorID,
		&i.RequestedByUserID,
		&i.Kind,
		&i.ArtifactFileID,
		&i.InputPayload,
		&i.SecretInput,
		&i.Status,
		&i.OutputPayload,
		&i.SecretOutput,
		&i.ErrorMessage,
		&i.DeadlineAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InventoryRevision,
		&i.InventoryAcknowledgedAt,
	)
	return i, err
}
