// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime_files.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnonymousToolConversation = `-- name: CreateAnonymousToolConversation :one
INSERT INTO agent_conversations(agent_id,user_id,source,title,metadata,settings)
VALUES ($1,NULL,'mcp-tool',$2,'{}','{}') RETURNING id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at, user_activity_at, notification_route_lost_at
`

type CreateAnonymousToolConversationParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Title   string      `json:"title"`
}

func (q *Queries) CreateAnonymousToolConversation(ctx context.Context, arg CreateAnonymousToolConversationParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, createAnonymousToolConversation, arg.AgentID, arg.Title)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserActivityAt,
		&i.NotificationRouteLostAt,
	)
	return i, err
}

const markRuntimeAttachment = `-- name: MarkRuntimeAttachment :execrows
INSERT INTO runtime_attached_files(run_id,path) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type MarkRuntimeAttachmentParams struct {
	RunID pgtype.UUID `json:"run_id"`
	Path  string      `json:"path"`
}

func (q *Queries) MarkRuntimeAttachment(ctx context.Context, arg MarkRuntimeAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRuntimeAttachment, arg.RunID, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
