// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_model_preferences.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAgentUserModelPreference = `-- name: DeleteAgentUserModelPreference :exec
DELETE FROM agent_user_model_preferences
WHERE agent_id = $1 AND user_id = $2
`

type DeleteAgentUserModelPreferenceParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAgentUserModelPreference(ctx context.Context, arg DeleteAgentUserModelPreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteAgentUserModelPreference, arg.AgentID, arg.UserID)
	return err
}

const getAgentUserModelPreference = `-- name: GetAgentUserModelPreference :one
SELECT provider_id, model, updated_at
FROM agent_user_model_preferences
WHERE agent_id = $1 AND user_id = $2
`

type GetAgentUserModelPreferenceParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

type GetAgentUserModelPreferenceRow struct {
	CatalogID pgtype.UUID        `json:"provider_id"`
	Model     string             `json:"model"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAgentUserModelPreference(ctx context.Context, arg GetAgentUserModelPreferenceParams) (GetAgentUserModelPreferenceRow, error) {
	row := q.db.QueryRow(ctx, getAgentUserModelPreference, arg.AgentID, arg.UserID)
	var i GetAgentUserModelPreferenceRow
	err := row.Scan(&i.CatalogID, &i.Model, &i.UpdatedAt)
	return i, err
}

const upsertAgentUserModelPreference = `-- name: UpsertAgentUserModelPreference :one
INSERT INTO agent_user_model_preferences (agent_id, user_id, provider_id, model)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id, user_id) DO UPDATE
SET provider_id = EXCLUDED.provider_id,
    model = EXCLUDED.model,
    updated_at = now()
RETURNING provider_id, model, updated_at
`

type UpsertAgentUserModelPreferenceParams struct {
	AgentID   pgtype.UUID `json:"agent_id"`
	UserID    pgtype.UUID `json:"user_id"`
	CatalogID pgtype.UUID `json:"provider_id"`
	Model     string      `json:"model"`
}

type UpsertAgentUserModelPreferenceRow struct {
	CatalogID pgtype.UUID        `json:"provider_id"`
	Model     string             `json:"model"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAgentUserModelPreference(ctx context.Context, arg UpsertAgentUserModelPreferenceParams) (UpsertAgentUserModelPreferenceRow, error) {
	row := q.db.QueryRow(ctx, upsertAgentUserModelPreference,
		arg.AgentID,
		arg.UserID,
		arg.CatalogID,
		arg.Model,
	)
	var i UpsertAgentUserModelPreferenceRow
	err := row.Scan(&i.CatalogID, &i.Model, &i.UpdatedAt)
	return i, err
}
